// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
#include "OI.h"
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
#include "SmartDashboard/SmartDashboard.h"
#include "Commands/AutonomousCommand.h"
#include "Commands/CatFwdPassRoutine.h"
#include "Commands/CatHighGoalRoutine.h"
#include "Commands/CatKill.h"
#include "Commands/CatThrowFwd.h"
#include "Commands/CatThrowHG.h"
#include "Commands/CatUnloadPos.h"
#include "Commands/CatUnloadRoutine.h"
#include "Commands/ClosePincer.h"
#include "Commands/DriveStraightAuto.h"
#include "Commands/DriveStraightTele.h"
#include "Commands/OneBallAuto.h"
#include "Commands/OpenPincer.h"
#include "Commands/StartCompressor.h"
#include "Commands/StopCompressor.h"
#include "Commands/TiltDown.h"
#include "Commands/TiltUp.h"
#include "Commands/TogglePincer.h"
#include "Commands/ToggleTilt.h"
#include "Commands/UseArcadeDriveCmd.h"
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
OI::OI() {
	// Process operator interface input here.
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
	rStick = new Joystick(3);
	
	cStick = new Joystick(1);
	
	catFwdPass3 = new JoystickButton(cStick, 3);
	catFwdPass3->WhenPressed(new CatFwdPassRoutine());
	catHG1 = new JoystickButton(cStick, 1);
	catHG1->WhenPressed(new CatHighGoalRoutine());
	catUnload2 = new JoystickButton(cStick, 2);
	catUnload2->WhenPressed(new CatUnloadRoutine());
	tilt5 = new JoystickButton(cStick, 5);
	tilt5->WhenPressed(new ToggleTilt());
	pinch6 = new JoystickButton(cStick, 6);
	pinch6->WhenPressed(new TogglePincer());
	lStick = new Joystick(2);
	
     
        // SmartDashboard Buttons
	SmartDashboard::PutData("TogglePincer", new TogglePincer());
	SmartDashboard::PutData("ToggleTilt", new ToggleTilt());
	SmartDashboard::PutData("DriveStraightAuto", new DriveStraightAuto());
	SmartDashboard::PutData("CatKill", new CatKill());
	SmartDashboard::PutData("CatUnloadRoutine", new CatUnloadRoutine());
	SmartDashboard::PutData("CatHighGoalRoutine", new CatHighGoalRoutine());
	SmartDashboard::PutData("OneBallAuto", new OneBallAuto());
	SmartDashboard::PutData("CatFwdPassRoutine", new CatFwdPassRoutine());
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
	SmartDashboard::PutData("Stop Compressor", new StopCompressor());
}
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
Joystick* OI::getRStick() {
	return rStick;
}
Joystick* OI::getCStick() {
	return cStick;
}
Joystick* OI::getLStick() {
	return lStick;
}
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
DriverStationLCD* OI::GetLCD(){
	return DriverStationLCD::GetInstance();
}
