// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
#ifndef ROBOTMAP_H
#define ROBOTMAP_H
#include "WPILib.h"
#include "WPILibExtensions/KomodoDrive.h"
/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
class RobotMap {
public:
	
	static SpeedController* driveLSpeed;
	static SpeedController* driveRSpeed;
	static RobotDrive* driveControl;
	static Gyro* driveGyro;
	static SpeedController* driveTurn;
	static PIDController* driveGyroPID;
	static Encoder* driveLEncoder;
	static Encoder* driveREncoder;
	static Relay* pincerPinch;
	static Relay* tiltTilt;
	static Compressor* compressorSysComp;
	static Encoder* catapultEncoder;
	static CANJaguar* catapultJag2;
	static CANJaguar* catapultJag3;
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	static void init();
};
#endif
