// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
#include "CatUnloadPos.h"
CatUnloadPos::CatUnloadPos() {
	// Use requires() here to declare subsystem dependencies
	// eg. requires(chassis);
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::catapult);
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
}
// Called just before this Command runs the first time
void CatUnloadPos::Initialize() {
	Robot::catapult->CatLimitOut(-.35, .35);
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INITIALIZE
	Robot::catapult->Enable();
	Robot::catapult->SetSetpoint(75.0);
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INITIALIZE
}
// Called repeatedly when this Command is scheduled to run
void CatUnloadPos::Execute() {
}
// Make this return true when this Command no longer needs to run execute()
bool CatUnloadPos::IsFinished() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ISFINISHED
	return Robot::catapult->OnTarget();
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ISFINISHED
}
// Called once after isFinished returns true
void CatUnloadPos::End() {
	Robot::catapult->CatLimitOut(-1.0, .35);
}
// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void CatUnloadPos::Interrupted() {
	End();
}
