// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
#include "UseArcadeDriveCmd.h"
UseArcadeDriveCmd::UseArcadeDriveCmd() {
	// Use requires() here to declare subsystem dependencies
	// eg. requires(chassis);
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::drive);
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	lStick = Robot::oi->getLStick();
	rStick = Robot::oi->getRStick();
}
// Called just before this Command runs the first time
void UseArcadeDriveCmd::Initialize() {
}
// Called repeatedly when this Command is scheduled to run
void UseArcadeDriveCmd::Execute() {
	float throttleCmd = lStick->GetRawAxis(Joystick::kZAxis)*-1;
	float turnCmd = rStick->GetRawAxis(Joystick::kYAxis);
	Robot::drive->UseArcadeDrive(throttleCmd, turnCmd);
}
// Make this return true when this Command no longer needs to run execute()
bool UseArcadeDriveCmd::IsFinished() {
	return true;
}
// Called once after isFinished returns true
void UseArcadeDriveCmd::End() {
	Robot::drive->UseArcadeDrive(0,0);
}
// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void UseArcadeDriveCmd::Interrupted() {
	End();
}
